In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(dpi=300)

In [3]:
df_elapsed_time= pd.read_csv('./발병_후_응급실_도착_소요시간_현황_시도별__20220625164517.csv',encoding='euc-kr')

df_census=pd.read_csv('2015_to_2020_인구총조사.csv',encoding='euc-kr')
#df_census 테이블에서 총인구/ 시도별 항목만 맞게 추출하기
df_census=df_census[df_census['항목']=="총인구[명]"]
cities=['서울특별시','부산광역시','대구광역시','인천광역시','광주광역시','대전광역시','울산광역시','세종특별자치시','경기도','강원도','충청북도','충청남도','전라북도','전라남도','경상북도','경상남도','제주특별자치도']



df_total_pop= pd.DataFrame()
for city in cities:
    df_total_pop.insert(cities.index(city),city,(df_census[df_census['행정구역별(읍면동)']==city]).squeeze())

df_total_pop.drop(['행정구역별(읍면동)','항목','단위'],axis=0)

,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,강원도,충청북도,충청남도,전라북도,전라남도,경상북도,경상남도,제주특별자치도
2015 년,9904312,3448737,2466052,2890451,1502881,1538394,1166615,204088,12479061,1518040,1589347,2107802,1834114,1799044,2680294,3334524,605619
2016 년,9805506,3440484,2461002,2913024,1501557,1535445,1166033,242507,12671956,1521751,1603404,2132566,1833168,1796017,2682169,3339633,623332
2017 년,9741871,3416918,2453041,2925967,1496172,1525849,1157077,276589,12851601,1521386,1611009,2162426,1826174,1792319,2677058,3345293,641757
2018 년,9673936,3395278,2444412,2936117,1490092,1511214,1150116,312374,13103188,1520391,1620935,2181416,1818157,1790352,2672902,3350350,658282
2019 년,9639541,3372692,2429940,2952237,1489730,1498839,1143692,338136,13300900,1520127,1629343,2188649,1807423,1787543,2668154,3347209,665048
2020 년,9586195,3349016,2410700,2945454,1477573,1488435,1135423,353933,13511676,1521763,1632088,2176636,1802766,1788807,2644757,3333056,670858
Unnamed: 9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_elapsed_time
#대전광역시,인천광역시,광주광역시,세종특별자치시,경기도,충청남도,전라남도,제주시
city_name=['서울광역시','부산광역시','대구광역시','인천광역시','광주광역시','대전광역시','울산광역시','세종특별자치시','경기도','강원도','충청북도','충청남도','전라북도','전라남도','경상북도','경상남도','제주특별자치도']
df_elapsed_time

,지역별(1),2014,2014.1,2014.2,2014.3,2014.4,2014.5,2014.6,2014.7,2014.8,...,2020,2020.1,2020.2,2020.3,2020.4,2020.5,2020.6,2020.7,2020.8,2020.9
0,지역별(1),계,30분 미만,30분~2시간,2~4시간,4~6시간,6~8시간,8~12시간,12~24시간,24시간 이상,...,계,30분 미만,30분~2시간,2~4시간,4~6시간,6~8시간,8~12시간,12~24시간,24시간 이상,미상/미입력
1,전체,5204708,503727,1341453,570460,319079,217099,298757,497914,1350502,...,4644231,355049,1292304,548170,294884,199524,269333,458539,1167541,58887
2,서울,1335698,131423,319257,135643,78965,55240,78141,127967,403988,...,1093564,81257,265752,116957,65449,44864,66889,114112,335912,2372
3,부산,231385,16504,68664,27905,14973,8897,11538,18476,61603,...,206589,8440,57348,23608,10954,7500,10129,17668,48543,22399
4,대구,189112,13834,45679,23813,13001,8428,11356,19152,49261,...,184440,11615,46653,21868,12369,8445,11022,21354,50441,673
5,인천,303653,30273,97346,31267,17094,11792,16582,25574,72433,...,309621,19578,113048,33134,18369,12339,16642,27805,68536,170
6,광주,154716,15120,31661,19649,10662,7087,9723,12703,46715,...,140056,9548,33571,18144,9844,6884,9427,14435,38133,70
7,대전,198119,23607,50143,22202,12485,8535,11583,18937,49058,...,154941,12766,41467,18524,9843,6686,8496,16219,40937,3
8,울산,76252,5913,20938,9232,4946,3004,3921,11404,16888,...,68075,5568,18847,8788,3845,2616,3534,9217,15660,-
9,세종,-,-,-,-,-,-,-,-,-,...,10006,560,1794,817,453,285,378,625,1479,3615
10,경기,1285308,121776,343748,142842,80821,55290,76389,132067,310694,...,1093766,84001,308906,136311,72210,49805,63737,110069,251421,17306
11,강원,169686,17737,39506,19151,10305,6727,9352,17201,48311,...,177957,12536,50345,22091,11457,7369,9460,15890,46388,2421
12,충북,114360,13416,33341,12286,6611,4358,5862,9054,28782,...,120027,12799,35983,13938,7740,4910,6294,10807,26882,674
13,충남,211267,19561,56594,23082,12548,8502,11029,17538,44162,...,209273,21145,64685,24477,13341,8901,12305,19776,44184,459
14,전북,153194,12976,36074,16487,9113,6024,7760,13325,40840,...,232001,18437,64279,27978,15105,9969,13352,20661,55379,6841
15,전남,102019,11921,26820,12203,6601,4547,6048,9050,24295,...,105867,8296,31415,14173,7880,4923,6031,8988,24020,141
16,경북,270572,31405,75798,30466,16341,11397,15676,25440,61634,...,195905,20190,62603,24124,12594,8512,10670,17909,38360,943
17,경남,268871,20344,56467,28476,15813,11321,14406,25686,64380,...,213356,17108,53405,27651,15048,9876,12740,20980,55968,580
18,제주,140496,17917,39417,15756,8800,5950,9391,14340,27458,...,128787,11205,42203,15587,8383,5640,8227,12024,25298,220